cesine/fantastic-lamp

.vscode/settings.json
src/constants/phraselist.test.ts
src/constants/phraselist.ts
src/lib/cipher.test.ts
src/lib/cipher.ts

Add phrases and simple cipher

---

.github/workflows/build.yml
.github/workflows/linkcheck.yml
.github/workflows/lint.yml
.github/workflows/playwright.yml
.github/workflows/storybook.yml
.github/workflows/test.yml

Only deploy storybook on main

---

src/App.tsx
src/components/alphabet/Alphabet.stories.tsx
src/components/cryptogram/Cryptogram.stories.tsx
src/components/modals/ShareMessageModal.tsx
src/components/navbar/Navbar.stories.tsx
src/components/navbar/Navbar.tsx
src/constants/settings.ts
src/lib/cipher.test.ts
src/lib/cipher.ts
src/lib/localStorage.ts
src/lib/quotes.ts
src/lib/share.test.ts
src/lib/share.ts
tests/share.spec.ts

Query params

---

.github/workflows/build.yml
src/App.tsx
src/components/alphabet/Alphabet.tsx
src/components/cryptogram/Cell.tsx
src/components/cryptogram/Cryptogram.stories.tsx
src/components/cryptogram/Cryptogram.tsx
src/context/AlertContext.tsx
src/lib/cipher.ts
src/lib/localStorage.ts
src/lib/share.ts

As a user I want to be able to load the app even if my ISP's IP address is on the block list and vercel is not supporting my IP address
-

Deploy build

---

src/lib/cipher.test.ts
src/lib/cipher.ts
tests/share.spec.ts

As a user i want the puzzle to use the same cipher if i refresh the page so that my guesses can be populated and I get the same cipher as my friends

Use random seed

---

src/App.tsx
src/constants/strings.ts
src/lib/cipher.test.ts
src/lib/cipher.ts
src/lib/quotes.ts
tests/share.spec.ts

fix refresh page populates guess

---

.github/workflows/build.yml
src/lib/quotes.ts

fix deployed app's open archived game

---

src/App.tsx
src/constants/strings.ts
tests/duplicate-letter.spec.ts

As a user I want to know if I have already used a letter so i can cahnge my guess for the current letter (or the previous letter)
After

Alert if the user already used that letter

---

public/index.html

As a app creater I want to be able to track users so that I can see what their doing, find any bugs and understand if their confused.

added google analytics tracking code

---

public/index.html
src/App.tsx
src/components/modals/StatsModal.stories.tsx
src/components/modals/StatsModal.tsx
src/lib/share.ts
tests/share.spec.ts

After 
> I solved Clueright's Cryptogram An encrypted message 794 0/26
> 
> IH
> 🟩🟩
> http://localhost:3000/?code=eyJndWVzc2VzIjpbXSwiaW5kZXgiOjc5NCwibWVzc2FnZSI6IkFuIGVuY3J5cHRlZCBtZXNzYWdlIiwic29sdXRpb24iOiJoaSJ9
(it shares the URL where you played, so normally that will be the URL of the real site)

Add link to site in share text

---

src/App.tsx
src/constants/settings.ts
tests/hint.spec.ts

As a  user I want more hints if I have already guessed the correct letter for today's hints
fixes #77

More hints

---

playwright.config.ts
src/App.tsx
src/components/navbar/Navbar.tsx
tests/analytics.spec.ts
tests/duplicate-letter.spec.ts
tests/game-lost.spec.ts
tests/hint.spec.ts
tests/share.spec.ts
tests/undo.spec.ts

Stabilize e2es

---

.env
README.md
src/App.tsx
src/components/modals/ShareMessageModal.tsx
src/components/navbar/Navbar.tsx
src/lib/stats.ts
tests/analytics.spec.ts
tests/duplicate-letter.spec.ts
tests/game-lost.spec.ts
tests/hint.spec.ts
tests/share.spec.ts
tests/undo.spec.ts

Add a bug report link button
Prevent Android users from trying the game since we know it doesnt work

Add beta experience

---

src/App.tsx
tests/hint.spec.ts

As a new user Its hard to find the settings to toggle into easy mode so I want to start in easy mode until i find the settings to switch to hard mode

Make easy default

---

.github/workflows/playwright-e2e.yml
.github/workflows/playwright.yml
public/index.html
tests/analytics.spec.ts
tests/hint.spec.ts

As an app designer I want to see real user data in google analytics, not data from end to end tests
https://support.google.com/analytics/answer/13296662
https://analytics.google.com/analytics/web/?pli=1#/analysis/p430507805/edit/-1A5T7BsSGmMJ4jJduJt6w

Update analytics testing

---

src/constants/quotelist.ts

as a puzzle solver I want lots of different quotes to come back to everyday.

added lots of quotes

---

src/App.tsx
src/lib/cipher.test.ts
src/lib/cipher.ts
tests/analytics.spec.ts
tests/duplicate-letter.spec.ts
tests/game-lost.spec.ts
tests/share.spec.ts

Fix random seed

---

src/App.tsx

by letting users use mobile game if on development urls

Make it possible to run mobile tests

---

src/components/cryptogram/Cell.tsx

Only focus the hidden input on iphone

---

src/lib/cipher.test.ts
src/lib/cipher.ts

for #100 i found we still have some days where the cipher is the same (a backwards alphabet)

Fix cipher when regenerated

---

src/App.tsx
src/components/modals/HeartModal.tsx
src/components/navbar/Navbar.stories.tsx
src/components/navbar/Navbar.tsx

Add the heart modal

---

src/lib/quotes.ts

We didnt add a test for this so this broke in the last commit on the branch in #116

Fix bug in archived game select

---

src/components/modals/HeartModal.tsx
src/components/modals/InfoModal.tsx
src/constants/quotelist.ts
src/lib/quotes.test.ts

As a cryptogram enthusiast I want a vast variety of quotes.  A new one per day for a whole year!

added quotes and fixed typos

---

playwright.config.ts
src/App.tsx
src/components/navbar/Navbar.tsx
tests/closed-beta.spec.ts
tests/share.spec.ts

As a game designer I want to make sure the closed beta is the default experience and that the potential user can use the link to get access
As a game designer I want to disable the buttons in the navbar so that they are not confusing

Closed beta test

---

src/App.tsx
tests/undo.spec.ts

Use backspace to delete a char
